#pragma once

#define GDT_KERNEL_CODE      0x08
#define GDT_KERNEL_DATA      0x10
#define GDT_USER_COMPAT_CODE 0x18
#define GDT_USER_DATA        0x20
#define GDT_USER_CODE        0x28
#define GDT_TSS              0x30

#ifndef OS_CONFIG_PROCESS_MAX_COUNT
#ifdef PROCESS_MAX_COUNT_CONFIG
#define OS_CONFIG_PROCESS_MAX_COUNT PROCESS_MAX_COUNT_CONFIG
#else
#define OS_CONFIG_PROCESS_MAX_COUNT 32
#endif
#endif

#ifndef OS_CONFIG_FILE_MAX_FD
#ifdef FILE_MAX_FD_CONFIG
#define OS_CONFIG_FILE_MAX_FD FILE_MAX_FD_CONFIG
#else
#define OS_CONFIG_FILE_MAX_FD 32
#endif
#endif

#ifndef OS_CONFIG_FILE_MAX_DIR_HANDLE
#ifdef FILE_MAX_DIR_HANDLE_CONFIG
#define OS_CONFIG_FILE_MAX_DIR_HANDLE FILE_MAX_DIR_HANDLE_CONFIG
#else
#define OS_CONFIG_FILE_MAX_DIR_HANDLE 32
#endif
#endif

#ifndef OS_CONFIG_WM_MAX_WINDOWS
#ifdef WM_MAX_WINDOWS_CONFIG
#define OS_CONFIG_WM_MAX_WINDOWS WM_MAX_WINDOWS_CONFIG
#else
#define OS_CONFIG_WM_MAX_WINDOWS 32
#endif
#endif

#ifndef PROCESS_MAX_COUNT_CONFIG
#define PROCESS_MAX_COUNT_CONFIG OS_CONFIG_PROCESS_MAX_COUNT
#endif

#ifndef FILE_MAX_FD_CONFIG
#define FILE_MAX_FD_CONFIG OS_CONFIG_FILE_MAX_FD
#endif

#ifndef FILE_MAX_DIR_HANDLE_CONFIG
#define FILE_MAX_DIR_HANDLE_CONFIG OS_CONFIG_FILE_MAX_DIR_HANDLE
#endif

#ifndef WM_MAX_WINDOWS_CONFIG
#define WM_MAX_WINDOWS_CONFIG OS_CONFIG_WM_MAX_WINDOWS
#endif

#define OS_CONFIG_PROCESS_MAX_COUNT_MIN   1
#define OS_CONFIG_PROCESS_MAX_COUNT_MAX   256
#define OS_CONFIG_FILE_MAX_FD_MIN         4
#define OS_CONFIG_FILE_MAX_FD_MAX         256
#define OS_CONFIG_FILE_MAX_DIR_HANDLE_MIN 4
#define OS_CONFIG_FILE_MAX_DIR_HANDLE_MAX 256
#define OS_CONFIG_WM_MAX_WINDOWS_MIN      1
#define OS_CONFIG_WM_MAX_WINDOWS_MAX      128

#if (PROCESS_MAX_COUNT_CONFIG < OS_CONFIG_PROCESS_MAX_COUNT_MIN) || \
    (PROCESS_MAX_COUNT_CONFIG > OS_CONFIG_PROCESS_MAX_COUNT_MAX)
#error "PROCESS_MAX_COUNT_CONFIG is out of supported range"
#endif

#if (FILE_MAX_FD_CONFIG < OS_CONFIG_FILE_MAX_FD_MIN) || \
    (FILE_MAX_FD_CONFIG > OS_CONFIG_FILE_MAX_FD_MAX)
#error "FILE_MAX_FD_CONFIG is out of supported range"
#endif

#if (FILE_MAX_DIR_HANDLE_CONFIG < OS_CONFIG_FILE_MAX_DIR_HANDLE_MIN) || \
    (FILE_MAX_DIR_HANDLE_CONFIG > OS_CONFIG_FILE_MAX_DIR_HANDLE_MAX)
#error "FILE_MAX_DIR_HANDLE_CONFIG is out of supported range"
#endif

#if (WM_MAX_WINDOWS_CONFIG < OS_CONFIG_WM_MAX_WINDOWS_MIN) || \
    (WM_MAX_WINDOWS_CONFIG > OS_CONFIG_WM_MAX_WINDOWS_MAX)
#error "WM_MAX_WINDOWS_CONFIG is out of supported range"
#endif

#if FILE_MAX_DIR_HANDLE_CONFIG > FILE_MAX_FD_CONFIG
#error "FILE_MAX_DIR_HANDLE_CONFIG must be <= FILE_MAX_FD_CONFIG"
#endif

#ifndef OS_CONFIG_SMP_MAX_CPUS
#define OS_CONFIG_SMP_MAX_CPUS 4
#endif

#ifndef OS_CONFIG_SMP_ENABLED
#define OS_CONFIG_SMP_ENABLED 1
#endif

#ifndef OS_CONFIG_SIGNAL_HANDLER_MAX_PER_PROCESS
#define OS_CONFIG_SIGNAL_HANDLER_MAX_PER_PROCESS 32
#endif

#ifndef OS_CONFIG_PENDING_SIGNAL_MAX_PER_PROCESS
#define OS_CONFIG_PENDING_SIGNAL_MAX_PER_PROCESS 64
#endif